[build]
  command = "NODE_OPTIONS='--max_old_space_size=4096' pnpm install --no-frozen-lockfile && pnpm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SITE_URL = "https://padokclub.netlify.app"
  NODE_VERSION = "20"
  NPM_FLAGS = "--prefer-offline --no-audit"
  NETLIFY_USE_YARN = "false"
  NETLIFY_USE_PNPM = "true"
  NODE_OPTIONS = "--max_old_space_size=4096"

[[plugins]]
  package = "@netlify/plugin-nextjs"